services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: db_workhub
    environment:
      - 'POSTGRES_DB=${DB:-workhub-db}'
      - 'POSTGRES_PASSWORD=${PASSWORD_DB:-workhub}'
      - 'POSTGRES_USER=${USER_DB:-workhub}'
    ports:
      - '5432:5432'
