spring:
  application:
    name: workhub
  datasource:
    url: jdbc:postgresql://${HOST_DB}:5432/${DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  docker:
    compose:
      enabled: false
auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES}
server:
  port: 9001
api:
  key:
    admin: ${API_KEY_ADMIN}
supabase:
  url: ${SUPABASE_URL}
  secret:
    key: ${SUPABASE_SECRET_KEY}
  storage:
    bucket: ${SUPABASE_STORAGE_BUCKET}